### ISSUE TITLE
minor adjustments on libmeta-dfgviewer after merge

### ISSUE THREAD

**Issue by rsteph-de** [MyCoRe-Org/libmeta#9]
This issue will fix some smaller issues with the newly merged dfgviewer classes.
We should try to keep this module 'compatible' to the other modules as good as possible.

**Comment by rsteph-de** [comment]
Done - For me it fits now!

**Comment by morpheus-87** [comment]
Can you give me any estimation, when version `0.8.1` will be released, @rsteph-de ?

**Comment by rsteph-de** [comment]
> Can you give me any estimation, when version `0.8.1` will be released, @rsteph-de ?

Before the release I would like to do some final polishing and some tests with the updated MODS API.
Maybe you could help and check on the develop-branch if my minor changes to the DublinCore / DFGViewer Metadata APIs (provided by your collegues) work for you.

We can schedule the release for next week.
